## Assignment 2 Part 3
### Import Modules

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
import statsmodels.api as sm

In [4]:
from sklearn.linear_model import LinearRegression, LogisticRegression

In [42]:
from statsmodels.stats.stattools import durbin_watson

In [7]:
pd.set_option('display.max_colwidth', None)

In [9]:
model = LogisticRegression()

In [10]:
df = pd.read_csv("APMM9-dataset10.csv")

In [11]:
df.head()

   actual predicted
0  label1    label1
1  label3    label3
2  label3    label3
3  label2    label3
4  label1    label1

In [72]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

In [16]:
# For Label 1
df["act_lab1"] = np.where(df.actual == "label1", 1, 0)
df["pred_lab1"] = np.where(df.predicted == "label1", 1, 0)

In [17]:
df

     actual predicted  act_lab1  pred_lab1
0    label1    label1         1          1
1    label3    label3         0          0
2    label3    label3         0          0
3    label2    label3         0          0
4    label1    label1         1          1
..      ...       ...       ...        ...
195  label1    label3         1          0
196  label3    label3         0          0
197  label3    label3         0          0
198  label3    label3         0          0
199  label3    label1         0          1

[200 rows x 4 columns]

In [76]:
TN, FP, FN, TP = confusion_matrix(df.act_lab1, df.pred_lab1).ravel()

In [77]:
precision = precision_score(df.act_lab1, df.pred_lab1)
recall = recall_score(df.act_lab1, df.pred_lab1)
f1 = f1_score(df.act_lab1, df.pred_lab1)

In [78]:
print(f"TP: {TP}")
print(f"FP: {FP}")
print(f"TN: {TN}")
print(f"FN: {FN}")
print(f"(Precision: {precision}")
print(f"(Recall: {recall}")
print(f"(F1 Score: {f1}")

TP: 71
FP: 15
TN: 89
FN: 25
(Precision: 0.8255813953488372
(Recall: 0.7395833333333334
(F1 Score: 0.7802197802197802

In [64]:
# For Label 2
df["act_lab2"] = np.where(df.actual == "label2", 1, 0)
df["pred_lab2"] = np.where(df.predicted == "label2", 1, 0)

In [65]:
TN, FP, FN, TP = confusion_matrix(df.act_lab2, df.pred_lab2).ravel()

In [66]:
precision = precision_score(df.act_lab2, df.pred_lab2)
recall = recall_score(df.act_lab2, df.pred_lab2)

In [67]:
print(f"TP: {TP}")
print(f"FP: {FP}")
print(f"TN: {TN}")
print(f"FN: {FN}")
print(f"(Precision: {precision}")
print(f"(Recall: {recall}")

TP: 24
FP: 24
TN: 138
FN: 14
(Precision: 0.5
(Recall: 0.631578947368421

In [91]:
# For Label 3
df["act_lab3"] = np.where(df.actual == "label3", 1, 0)
df["pred_lab3"] = np.where(df.predicted == "label3", 1, 0)

In [92]:
TN, FP, FN, TP = confusion_matrix(df.act_lab3, df.pred_lab3).ravel()

In [93]:
precision = precision_score(df.act_lab3, df.pred_lab3)
recall = recall_score(df.act_lab3, df.pred_lab3)

In [94]:
print(f"TP: {TP}")
print(f"FP: {FP}")
print(f"TN: {TN}")
print(f"FN: {FN}")
print(f"(Precision: {precision}")
print(f"(Recall: {recall}")

TP: 48
FP: 18
TN: 116
FN: 18
(Precision: 0.7272727272727273
(Recall: 0.7272727272727273

In [81]:
macro_precision = precision_score(df['actual'], df['predicted'], average='macro')

In [83]:
macro_precision

0.6842847075405215

In [84]:
macro_recall = recall_score(df['actual'], df['predicted'], average='macro')

In [85]:
macro_recall

0.6994783359914939

In [87]:
weight_precision = precision_score(df['actual'], df['predicted'], average='weighted')

In [88]:
weight_precision

0.7312790697674418

In [95]:
weight_recall = recall_score(df['actual'], df['predicted'], average='weighted')

In [96]:
weight_recall

0.715